name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true

      - name: Build
        run: hugo --buildFuture --minify --environment production

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: blog
          directory: public
          # Direct Upload could not change the production branch
          branch: main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      # - name: n8n webhook for essay
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: https://n8n.reorx.com/webhook/94ef0293-22d5-4d4d-84ec-e668e24999dd
      #     method: 'GET'
      # - name: n8n webhook for blog
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: https://n8n.reorx.com/webhook/9a883425-69e8-4add-b061-9371d85003b3
      #     method: 'GET'
